### GET request to get all todos
GET http://localhost:9090/todos
Accept: application/json

### POST request to add todo
POST http://localhost:9090/todos
Content-Type: application/json

{
  "id": "1",
  "item": "Test",
  "completed": false
}

###GET request to get specific todo with id
GET http://localhost:9090/todos/3

###PATCH change 'completed' status of specific todo with id
PATCH http://localhost:9090/todos/3
